name: CICD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:4.5.0
      options: --user 1001
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: ( cd web && npm install && (npm start &) )
      - run: cypress run --project=web
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: ( cd functions && npm install && npm run build )
      - run: ( cd web && npm install && npm run build )
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
