name: CICD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.13.0-chrome80-ff74
      options: --user 1001
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: ( cd web && npm install && npm start )
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
      - uses: cypress-io/github-action@v1
        with:
          browser: firefox
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: ( cd functions && npm install && npm run build )
      - run: ( cd web && npm install && npm run build )
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
